image: devcurmudgeon/foo

before_script:
- sh ./install_dependencies.sh
- apt-get update -qq && apt-get install -y -qq git
- git clone git://git.baserock.org/baserock/baserock/definitions ../definitions

cache:
  paths:
  - "$YBD_base"

stages:
- pep8
- cache_keys
- build
- test
- deploy

check_pep8:
  stage: pep8
  script: "pep8"

cache_keys_v1:
  stage: cache_keys
  variables:
    YBD_artifact_version: "1"
    YBD_mode: "keys-only"
  script:
  - cd ../definitions
  - git checkout baserock-14.40
  - ../ybd/ybd.py ci x86_64
  - echo ci.b9de86669ce182e60e3f9445e6394b478b67a2c73b4c0764491c158c5f2569e9 > expected.result
  - diff expected.result ybd.result

cache_keys_v6:
  stage: cache_keys
  variables:
    YBD_artifact_version: "6"
    YBD_mode: "keys-only"
  script:
  - cd ../definitions
  - git checkout GENIVI-M1.0
  - ../ybd/ybd.py ci x86_64
  - echo ci.d9dec300a7cb2bc273dc6846e69a11b7f3ad304462f3a4c6ce8c5ab6ead11647 > expected.result
  - diff expected.result ybd.result

check_build:
  stage: build
  variables:
    YBD_check_definitions: "exit"
  script:
  - ./ybd.py definitions/systems/minimal-system-x86_64-generic.morph x86_64

check_build_no_kbas:
  stage: build
  variables:
    YBD_check_definitions: "exit"
    YBD_kbas_url: "false-url"
  script:
  - ./ybd.py definitions/strata/build-essential.morph x86_64
